import ollama


# Name of the local Ollama model used by the application.
# The model must already be installed with:
# ollama pull llama3.2:3b
MODEL_NAME = "llama3.2:3b"


def ask_ollama(prompt: str) -> str:
    """
    Send a prompt to the local Ollama model and return its response.

    Args:
        prompt: The question or instruction sent to the model.

    Returns:
        The text generated by Ollama.

    Raises:
        TypeError: If the prompt is not a string.
        ValueError: If the prompt is empty.
        RuntimeError: If Ollama cannot be reached or returns no content.
    """

    # Validate that the supplied prompt is text.
    if not isinstance(prompt, str):
        raise TypeError("Prompt must be a string.")

    # Remove unnecessary spaces and verify that something remains.
    cleaned_prompt = prompt.strip()

    if not cleaned_prompt:
        raise ValueError("Prompt cannot be empty.")

    try:
        # Send the user's prompt to the local Ollama server.
        #
        # The messages structure follows the common chat format:
        # - role: identifies who sent the message
        # - content: contains the actual prompt
        response = ollama.chat(
            model=MODEL_NAME,
            messages=[
                {
                    "role": "user",
                    "content": cleaned_prompt,
                }
            ],
        )

    except Exception as exc:
        # Convert Ollama connection or execution errors into
        # a clearer application-level error.
        raise RuntimeError(
            f"Could not communicate with Ollama: {exc}"
        ) from exc

    # Safely retrieve the generated text from the response.
    #
    # Expected response structure:
    # {
    #     "message": {
    #         "content": "Generated answer"
    #     }
    # }
    content = response.get("message", {}).get("content")

    # Ensure the model actually returned useful text.
    if not content:
        raise RuntimeError(
            "Ollama returned a response without content."
        )

    # Return the cleaned model response to the caller.
    return content.strip()